version: '2'
services:
  db:
    image: mariadb:10.1
    container_name: ipeer_db
    environment:
      - MYSQL_ROOT_PASSWORD=randompassword
      - MYSQL_DATABASE=ipeer
      - MYSQL_USER=ipeer
      - MYSQL_PASSWORD=ipeer
    ports:
      - "13306:3306"
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - "13306:3306"
  app: &app
    image: ubcctlt/ipeer-app
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: ipeer_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - IPEER_DB_HOST=db
      - IPEER_DB_USER=ipeer
      - IPEER_DB_PASSWORD=ipeer
      - IPEER_DEBUG=2
      - IPEER_SESSION_SAVE=database
      # uncomment to test Caliper
      # - CALIPER_HOST=https://caliper.imsglobal.org/caliper/44c6173f-907f-40c5-8c93-a1acfaa6485c/message
      # - CALIPER_API_KEY=44c6173f-907f-40c5-8c93-a1acfaa6485c
      # - CALIPER_BASE_URL=http://localhost.test.com/
      # - CALIPER_ACTOR_BASE_URL=http://www.ubc.ca/%s
      # - CALIPER_ACTOR_UNIQUE_IDENTIFIER_PARAM=username
      #- IPEER_AUTH=Ldap
      #- IPEER_AUTH_LDAP_host=ldap.example.com
      #- IPEER_AUTH_LDAP_port=636
    depends_on:
      - db
  worker: &worker
    <<: *app
    container_name: ipeer_worker
    command: cake/console/cake worker run
    ports:
      - "9002:9000"
  web:
    image: ubcctlt/ipeer-web
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: ipeer_web
    volumes:
      - ./app/webroot:/var/www/html
    environment:
      - NGINX_FASTCGI_PASS=ipeer_app:9000
    ports:
      - "8080:80"
    depends_on:
      - app

  # for running unit tests
  app-unittest:
    image: ubcctlt/ipeer-app
    build:
      context: .
      dockerfile: Dockerfile-app-unittest
    container_name: ipeer_app_unittest
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    environment:
      - IPEER_DB_HOST=db
      - IPEER_DB_USER=ipeer
      - IPEER_DB_PASSWORD=ipeer
      - IPEER_DB_NAME=ipeer_test
      - IPEER_DEBUG=2
      - IPEER_SESSION_SAVE=database
      - SELENIUM_HOST=selenium-local
      - SELENIUM_BROWSER=chrome
      #- SELENIUM_BROWSER=firefox
      - SERVER_TEST=http://ipeer_web_unittest
      #- IPEER_AUTH=Ldap
      #- IPEER_AUTH_LDAP_host=ldap.example.com
      #- IPEER_AUTH_LDAP_port=636
    depends_on:
      - db
  # for running unit tests
  web-unittest:
    image: ubcctlt/ipeer-web
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: ipeer_web_unittest
    volumes:
      - ./app/webroot:/var/www/html
    environment:
      - NGINX_FASTCGI_PASS=ipeer_app_unittest:9000
    ports:
      - "8081:80"
    depends_on:
      - app-unittest
